### PR TITLE
Change queue creation methond to run on OpenCL 1.2

### PR DESCRIPTION
**Pull request by misha-plus**
Hello.
I used this library -- looks good. 
But library can't be compiled at my Mac. It has OpenCL 1.2, but the library uses the method from OpenCL 2.0. So I changed method from `clCreateCommandQueueWithProperties` to `clCreateCommandQueue`

Tests are working but images tests aren't work in my configuration.

### CODE REVIEW

**Comment by microo8** [comment]
Can you do it please so, that when it runs OpenCL 2.0, it will call `clCreateCommandQueueWithProperties` and when it runs OpenCL 1.2 `clCreateCommandQueue`.

It would be great if it where in a C wrapper that checks the `__OPENCL_VERSION__` preprocessor macro

**Comment by misha-plus** [comment]
Ok. I'll do

**Comment by misha-plus** [comment]
I updated PR. The define which you propose available only in kernel code as I understand. I looked to headers of OpenCL from macOS and Khronos. There are `CL_VERSION_\d_\d`defines, I used `CL_VERSION_2_0` to determine for version 2+. Also, I added stub method when OpenCL 2+ isn't available for `clCreateCommandQueueWithProperties`.

Moreover, now I think that if OpenCL has backward compatibility with OpenCL 1.x there is no reason in looking for the version of OpenCL and usage `clCreateCommandQueue` is enough because there are no properties are used. Don't know is this have sense.

**Comment by microo8** [comment]
I was thinking about making an function like `createCommandQueue` and in it's body you check if there is `CL_VERSION_2_0` and then use `clCreateCommandQueueWithProperties` otherwise `clCreateCommandQueue`.

Then from go just call the new `createCommandQueue` function.
But this is good enough.

**Pull request merged**
